services:
  ebank-discovery-service:
    build: ./discovry-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.101:8761/actuator/health"]
      interval: 10s
  ebank-config-service:
    build: ./config-service
    container_name: ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.101:9999/actuator/health"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
    depends_on:
      ebank-discovery-service:
        condition: service_healthy
  ebank-customer-service:
    build: ./customer-service
    container_name: ebank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.101:8081/actuator/health"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy
  ebank-account-service:
    build: ./account-service
    container_name: ebank-account-service
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:9999
    depends_on:
      ebank-customer-service:
        condition: service_healthy
  ebank-gateway-service:
    build: ./gateway-service
    container_name: ebank-gateway-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy